name: run_test_pipelines
on:
  workflow_dispatch:
  push:
   branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nf-core/setup-nextflow@v1
      - name: Set up Docker
        run: |
          apt-get update
          apt-get install -y docker.io
          service docker start
      - name: Docker Illumina AQUASCOPE
        run: | 
          nextflow run main.nf --resume -profile docker,test_illumina -entry AQUASCOPE --outdir ~/projects/tmp/complete
